appbuilder:
  container_name: appbuilder
  build: .
  mem_limit: 512m
  ports:
   - "8080:8080"
   - "50000:50000"
  env_file:
   - ./local.env
slave:
  container_name: slave
  image: sillsdev/appbuilder-agent:bloom
  mem_limit: 1024m
  links:
    - appbuilder:appbuilder-master
  command: -master http://appbuilder-master:8080
